name: 'Compile Mermaid in Markdown'
description: 'Compile *.mermaid, *.mmd files or *.md with mermaid codeblocks and output svg'
branding:
  icon: 'grid'
  color: 'green'
inputs:
  files:
    description: 'the path to the files to compile'
    required: true
  output:
    description: 'Where to output the file - std otherwise'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: "/entrypoint.sh"
  args:
    - ${{ inputs.output }}
    - ${{ inputs.files }}
